import { FormEvent, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiRequest } from '../api/client';

type InvitationPreview = { name: string; email: string; clinicName: string; expiresAt: string };
export function SecretaryInvitationAcceptancePage() {
  const [params] = useSearchParams(); const token = params.get('token') ?? '';
  const [preview, setPreview] = useState<InvitationPreview | null>(null); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [accepted, setAccepted] = useState(false);
  useEffect(() => { if (!token) { setError('This invitation link is invalid or incomplete.'); setLoading(false); return; } void apiRequest<InvitationPreview>(`/practice-staff/invitations/preview?token=${encodeURIComponent(token)}`).then(setPreview).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Unable to open this invitation.')).finally(() => setLoading(false)); }, [token]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (password !== confirmation) { setError('Passwords do not match.'); return; } setSubmitting(true); try { await apiRequest('/practice-staff/invitations/accept', { method: 'POST', body: { token, password } }); setAccepted(true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to accept this invitation.'); } finally { setSubmitting(false); } }
  if (loading) return <main className="centered-page"><section className="auth-panel" role="status">Opening your invitation…</section></main>;
  if (accepted) return <main className="centered-page"><section className="auth-panel invitation-success"><span aria-hidden="true">✓</span><h1>Account Created</h1><p>Your Secretary account is ready. Sign in to continue.</p><Link className="link-button" to="/login">Sign In</Link></section></main>;
  return <main className="auth-page"><section className="auth-panel"><Link className="brand" to="/">CLINIC QUEUEING</Link><div className="auth-heading"><p className="eyebrow">Secretary invitation</p><h1>Complete your account</h1>{preview ? <p>{preview.name}, you were invited to join <strong>{preview.clinicName}</strong>.</p> : null}</div>{error && !preview ? <><div className="form-error" role="alert">{error}</div><p><Link to="/login">Return to sign in</Link></p></> : preview ? <form className="stack" onSubmit={(event) => void submit(event)}><label>Email<input value={preview.email} disabled /></label><label>Create Password<input type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><label>Confirm Password<input type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} required /></label>{error ? <div className="form-error" role="alert">{error}</div> : null}<button className="primary" type="submit" disabled={submitting || !password || !confirmation}>{submitting ? 'Creating account…' : 'Create Secretary Account'}</button><p className="invitation-scope-note">Accepting creates your account only. Clinic authority is granted separately by the Doctor.</p></form> : null}</section></main>;
}
