export enum ClinicSecretaryAuthorityBundle {
  QUEUE_AND_CLINIC_DAY_OPERATIONS = 'QUEUE_AND_CLINIC_DAY_OPERATIONS',
  APPOINTMENTS_AND_PATIENT_INTAKE = 'APPOINTMENTS_AND_PATIENT_INTAKE',
  CLINIC_CONFIGURATION_DRAFTING = 'CLINIC_CONFIGURATION_DRAFTING',
  REPORTS_VIEW_ONLY = 'REPORTS_VIEW_ONLY',
}

export const CLINIC_SECRETARY_AUTHORITY_BUNDLES = Object.freeze(
  Object.values(ClinicSecretaryAuthorityBundle),
);
